service: boletealo-ms-eventos

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole
  environment:
    EVENTOS_TABLE: ${self:service}-eventos-${sls:stage}
    JWT_SECRET: ${ssm:/boletealo/jwt_secret}
  httpApi:
    cors: true

functions:
  listEventos:
    handler: handler.list_eventos
    events:
      - httpApi:
          path: /events
          method: GET

  getEvento:
    handler: handler.get_evento
    events:
      - httpApi:
          path: /events/{eventoId}
          method: GET

  createEvento:
    handler: handler.create_evento
    timeout: 15
    events:
      - httpApi:
          path: /events
          method: POST

  listMisEventos:
    handler: handler.list_mis_eventos
    events:
      - httpApi:
          path: /events/mis-eventos
          method: GET

  toggleEvento:
    handler: handler.toggle_evento
    events:
      - httpApi:
          path: /events/{eventoId}/toggle
          method: PATCH

resources:
  Resources:
    EventosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.EVENTOS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: eventoId
            AttributeType: S
          - AttributeName: categoria
            AttributeType: S
        KeySchema:
          - AttributeName: eventoId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: categoria-index
            KeySchema:
              - AttributeName: categoria
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
