service: boletealo-ms-incidentes

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole
  environment:
    INCIDENTES_TABLE: ${self:service}-incidentes-${sls:stage}
    EVIDENCIAS_BUCKET: ${self:service}-evidencias-${sls:stage}
  httpApi:
    cors: true

functions:
  createIncidente:
    handler: handler.create_incidente
    timeout: 30
    events:
      - httpApi:
          path: /incidentes
          method: POST

  listMyIncidentes:
    handler: handler.list_my_incidentes
    events:
      - httpApi:
          path: /incidentes
          method: GET

  getIncidente:
    handler: handler.get_incidente
    events:
      - httpApi:
          path: /incidentes/{incidenteId}
          method: GET

  getUploadUrl:
    handler: handler.get_upload_url
    events:
      - httpApi:
          path: /incidentes/upload-url
          method: POST

resources:
  Resources:
    IncidentesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.INCIDENTES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: incidenteId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: incidenteId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    EvidenciasBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.EVIDENCIAS_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: [GET, PUT, POST]
              AllowedOrigins: ["*"]
              MaxAge: 3600

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
