service: boletealo-ms-pagos

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole
  environment:
    PAGOS_TABLE: ${self:service}-pagos-${sls:stage}
    MS_TICKETS_URL: ${ssm:/boletealo/ms_tickets_url}
    JWT_SECRET: ${ssm:/boletealo/jwt_secret}
  httpApi:
    cors: true

functions:
  procesarPago:
    handler: handler.procesar_pago
    timeout: 30
    events:
      - httpApi:
          path: /pagos/procesar
          method: POST

  getPago:
    handler: handler.get_pago
    timeout: 15
    events:
      - httpApi:
          path: /pagos/{pagoId}
          method: GET

resources:
  Resources:
    PagosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PAGOS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pagoId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: pagoId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
