service: boletealo-ms-tickets

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  iam:
    role: arn:aws:iam::${aws:accountId}:role/LabRole
  environment:
    TICKETS_TABLE: ${self:service}-tickets-${sls:stage}
    MS_EVENTOS_URL: ${ssm:/boletealo/ms_eventos_url}
    JWT_SECRET: ${ssm:/boletealo/jwt_secret}
  httpApi:
    cors: true

functions:
  buyTicket:
    handler: handler.buy_ticket
    timeout: 30
    events:
      - httpApi:
          path: /tickets
          method: POST

  listMyTickets:
    handler: handler.list_my_tickets
    timeout: 15
    events:
      - httpApi:
          path: /tickets
          method: GET

  getTicket:
    handler: handler.get_ticket
    timeout: 15
    events:
      - httpApi:
          path: /tickets/{ticketId}
          method: GET

resources:
  Resources:
    TicketsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TICKETS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: ticketId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: ticketId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
